### ISSUE TITLE
No handlers could be found for logger "zerorpc.channel"

### ISSUE THREAD

**Issue by nive7s** [0rpc/zerorpc-crosstests#1]
Hi, I hope this is a good place to post my question and I'm aware that this could be the dumbest question ever but I'm new to 0rpc and not very expert in python too, but I'd like to learn.

I'm trying to replicate the HelloWorld example from the 0rpc site (http://www.zerorpc.io/).

I've installed all the prerequisite and created the py and node files.
I launch the python script and as soon as I launch the node script i get this error (on python side):

`No handlers could be found for logger "zerorpc.channel"`

What am I missing here?

My scrips are just a copy and paste from the ones on the site. I'm working on a rasperry pi 2 model B. 
Python v2.7.9
Node v6.9.2

ThankYou for your time

**Comment by bombela** [comment]
You can setup a basic logger with something like that:

```
import logging

logging.DefaultConfig()
```

(Check the logging package doc)
